[project]
authors = ["Mitchell Robert Vollger <mrvollger@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "FIRE"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test-data = { cmd = [
  "cd",
  "$INIT_CWD",
  "&&",
  "mkdir",
  "-p",
  "fire-test-data",
  "&&",
  "aws",
  "s3",
  "--no-sign-request",
  "sync",
  "s3://stergachis-public1/FIRE/test-data",
  "fire-test-data/",
] }
test = { cmd = [
  "cd",
  "$INIT_CWD/fire-test-data",
  "&&",
  "snakemake",
  "-s",
  "$PIXI_PROJECT_ROOT/workflow/Snakefile",
  "--configfile",
  "test.yaml",
], depends_on = [
  "test-data",
], clean-env = true }

fire = { cmd = "cd $INIT_CWD && snakemake -s $PIXI_PROJECT_ROOT/workflow/Snakefile" }

[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
awscli = "2.22"
taplo = "*"

[pypi-dependencies]
snakemake-executor-plugin-slurm = "*"
