```{r, echo=FALSE}
system("mkdir -p Figures")

system("mkdir -p Tables")
source('Rscripts/utils.R')
library(valr)
```


```{r}
min_frac_phased=0.3
min_phased = 10
# 24,535,850-24,549,744
chrx_bp = 24535850
```

```{r}
#f="results/GM12878_130X/hap1-vs-hap2/FIRE.hap.differences.bed"
#a=my_read_bed(f)
f="results/UDN318336/hap1-vs-hap2/FIRE.hap.differences.bed"
b=my_read_bed(f)
f="results/GM12878_pacbiome/hap1-vs-hap2/FIRE.hap.differences.bed"
c=my_read_bed(f)
f="results/HG002_pacbiome/hap1-vs-hap2/FIRE.hap.differences.bed"
d=my_read_bed(f)
f="results/GM20129_PS00447/hap1-vs-hap2/FIRE.hap.differences.bed"
e=my_read_bed(f)
f="results/HG02630_PS00445/hap1-vs-hap2/FIRE.hap.differences.bed"
f=my_read_bed(f)

imprinted=my_read_bed("data/lcl_dmr_coordinates_Akbari.bed.gz")
pdf=bind_rows(
    list(b,c,d,e,f)
    ) %>%
    bed_map(imprinted, imprinted=(length(V4) > 0)) %>%
    replace_na(list(imprinted=FALSE)) %>%
    group_by(sample)%>%
    mutate(
        #p_cor = p_value * n(),
        p_adjust = p.adjust(p_value, method="BH"),
    ) %>%
    data.table()

tdf = copy(pdf)
cond = !(pdf$sample %in% c("UDN318336", "HG02630_PS00445", "GM20129_PS00447"))
h1=grep("hap1", colnames(pdf))
h2=grep("hap2", colnames(pdf))
for(i in seq(length(h1))){
    c1 = h1[i]
    c2 = h2[i]
    pdf[cond][[c1]] = tdf[cond][[c2]]
    pdf[cond][[c2]] = tdf[cond][[c1]]
}

pdf
```


```{r}
SM="GM20129_PS00447"
SM="HG02630_PS00445"
SM="UDN318336"

tdf = pdf %>% 
    filter(sample==SM) %>%
    mutate(
        col=case_when(diff < 0 ~ "darkred", TRUE ~ "darkblue"),
        case=case_when(diff < 0 ~ -1, TRUE ~ 1),
        ct=chrom,
        st=start,
        en=end,
    )

single_out_chr = "chr14"
my_comparisons <- list( 
    c(single_out_chr, "other"),
    c("left of chr13 BP", "right of chr13 BP"),
    c("other", "left of chr13 BP"),
    c("other", "right of chr13 BP")
)
chr13.df=tdf %>% 
    mutate(
        lfc=log2(hap1_frac_acc/hap2_frac_acc)
    ) %>%
    mutate(
        location=case_when(
            ct == single_out_chr ~ single_out_chr,
            ct == "chrX" & st > chrx_bp ~ "right of chrX BP",
            ct == "chrX" & en < chrx_bp ~ "left of chrX BP",
            ct == "chr13" & st > 35480297 ~ "right of chr13 BP",
            ct == "chr13" & en < 35480297 ~ "left of chr13 BP",
            TRUE ~ "other"
        ),
        bin=case_when(
            ct == "chrX" & st > chrx_bp ~ "right of chrX BP",
            ct == "chrX" & en < chrx_bp ~ "left of chrX BP",
            ct != "chr13" ~ "other",
            en < 35480297 ~ "left of chr13 BP",
            en < 35480297 + 1*19.72e6 ~ "bin 1",
            en < 35480297 + 2*19.72e6 ~ "bin 2",
            en < 35480297 + 3*19.72e6 ~ "bin 3",
            en < 35480297 + 4*19.72e6 ~ "bin 4",
            en < 35480297 + 75e6 ~ "bin 5",
            en < 35480297 + 80e6 ~ "bin 6",
        )
    ) %>%
    mutate(
        fill=case_when(
            ct == "chr13" ~ "darkred",
            TRUE ~ NA,
        ),
    ) %>%
    filter(imprinted==0.0)


summary_diff = chr13.df %>%
    group_by(location) %>%
    summarise(
        per_diff=100*median(diff),
        n=n(),
    )
    
summary_diff
p = chr13.df %>%
    ggviolin(y = "diff", x="location",
        draw_quantiles = 0.5,
        rug = FALSE,
        fill="location",
        alpha=0.5,
    ) +
    stat_compare_means(
        #label="{p.format}{p.signif}",
        #label.y = c(0.9, 0.9, 1, 1.1),
        comparisons=my_comparisons,
        method="wilcox.test",
        size=2,
        method.args=list(alternative="greater"),
    ) +
    geom_text(
        data = summary_diff,
        aes(
            x=location,
            y=-0.8,
            label=paste0(
                " n = ", comma(n), "\n ",
                round(per_diff,2), "%"
            )
        ),
        vjust=1,
        hjust=0,
        size=1.75
    ) +
    scale_y_continuous("Difference between paternal and maternal accessibility", labels=percent) +
    scale_fill_manual(
        values=c(
            `other`=NA,
            `left of chrX BP`=NA,
            `right of chrX BP`=NA,
            `chr8`=NA,
            `left of chr13 BP`="darkblue",
            `right of chr13 BP`="darkred"
        )
    )+
    my_grid() +
    theme(legend.position="none")

#ggadjust_pvalue(p,label = "{p.adj.format}{p.adj.signif}")
my_ggsave("Figures/r1_{SM}_violin_hap1_vs_hap2.pdf", height=3, width=5)

```

```{r}
summary_diff = chr13.df %>%
    group_by(bin) %>%
    summarise(
        per_diff=100*median(diff),
        n=n(),
    )

bins = unique(chr13.df$bin); bins

my_comparisons= list(
    c("other", "bin 1"),
    c("other", "bin 2"),
    c("other", "bin 3"),
    c("other", "bin 4"),
    c("left of chr13 BP", "bin 1"),
    c("left of chr13 BP", "bin 2"),
    c("left of chr13 BP", "bin 3"),
    c("left of chr13 BP", "bin 4")
)

chr13.df %>%
    ggviolin(y = "diff", x="bin",
        draw_quantiles = 0.5,
        rug = FALSE,
        fill="bin",
        alpha=0.5,
    ) +
    stat_compare_means(
        #label="{p.format}{p.signif}",
        #label.y = c(0.9, 0.9, 1, 1.1),
        comparisons=my_comparisons,
        method="wilcox.test",
        size=2,
        method.args=list(alternative="greater"),
    ) + my_grid() +
     geom_text(
        data = summary_diff,
        aes(
            x=bin,
            y=-0.8,
            label=paste0(
                " n = ", comma(n), "\n ",
                round(per_diff,3), "%"
            )
        ),
        vjust=1,
        hjust=0,
        size=1.75
    ) +
    scale_y_continuous("Difference between paternal and maternal accessibility", labels=percent) +
    my_grid() +
    theme(legend.position="none")
my_ggsave("Figures/r1_{SM}_all_violin_hap1_vs_hap2.pdf")
```



#
# transcript version
#

```{r}
#transcripts=fread("isoseq-x-inactivation-affects/transcripts.bed.gz")
transcripts=fread("isoseq-x-inactivation-affects/transcripts.old.data.genes.bed.gz", fill=TRUE) 
colnames(transcripts) = c("chrom", "start", "end", "sample", "HP", "x", "y", "z", "Gene") 
transcripts = transcripts %>% filter(!grepl("_", chrom))


grouped_transcripts = transcripts %>%
    group_by(chrom, sample, Gene) %>%
    summarise(
        st=min(start),
        max_start=max(start),
        en=max(end),
        n=n(),
        unphased=sum(is.na(HP)),
        H1 = sum(HP=="1", na.rm=T),
        H2 = sum(HP=="2", na.rm=T),
        phased = H1+H2,
    ) 
    
grouped_transcripts %>%
    filter(Gene == "XIST") %>%
    arrange(-n)
```

```{r}
min_frac_phased=0.3
min_phased = 10
# 24,535,850-24,549,744
chrx_bp = 24535850

filtered = grouped_transcripts %>% 
    #filter(
    #    Gene != "novel",
    #    Gene != "Novel"
    #) %>%
    filter(phased>=min_phased) %>%
    filter(phased/n >= min_frac_phased) %>%
    mutate(
        ct=chrom,
        diff = H1/phased - H2/phased,
    ) %>%
    filter(
        en-st < 5e5
    ) 
filtered %>%
    filter(Gene == "XIST")

single_out_chr = "chr14"
my_comparisons <- list(
    c(single_out_chr, "other"),
    c("left of chr13 BP", "right of chr13 BP"),
    c("other", "left of chr13 BP"),
    c("other", "right of chr13 BP")
)
chr13.df=filtered %>%
    mutate(
        location=case_when(
            #ct == "chrX" & Gene == "XIST" ~ "XIST",
            ct == single_out_chr ~ single_out_chr,
            #ct == "chrX" & st > chrx_bp ~ "right of chrX BP",
            #ct == "chrX" & en < chrx_bp ~ "left of chrX BP",
            ct == "chrX" ~ "chrX", 
            ct == "chr13" & st > 35480297 ~ "right of chr13 BP",
            ct == "chr13" & en < 35480297 ~ "left of chr13 BP",
            TRUE ~ "other"
        ),
        bin=case_when(
            ct == "chrX" & st > chrx_bp ~ "right of chrX BP",
            ct == "chrX" & en < chrx_bp ~ "left of chrX BP",
            ct != "chr13" ~ "other",
            en < 35480297 ~ "left of chr13 BP",
            en < 35480297 + 1*19.72e6 ~ "bin 1",
            en < 35480297 + 2*19.72e6 ~ "bin 2",
            en < 35480297 + 3*19.72e6 ~ "bin 3",
            en < 35480297 + 4*19.72e6 ~ "bin 4",
            en < 35480297 + 75e6 ~ "bin 5",
            en < 35480297 + 80e6 ~ "bin 6",
        )
    ) %>%
    mutate(
        fill=case_when(
            ct == "chr13" ~ "darkred",
            TRUE ~ NA,
        ),
    )


summary_diff = chr13.df %>%
    group_by(location, sample) %>%
    summarise(
        per_diff=100*median(diff),
        n=n(),
    )
summary_diff
p = chr13.df %>%
    ggviolin(y = "diff", x="location",
        draw_quantiles = 0.5,
        rug = FALSE,
        fill="location",
        alpha=0.5,
    ) +
    stat_compare_means(
        #label="{p.format}{p.signif}",
        #label.y = c(0.9, 0.9, 1, 1.1),
        comparisons=my_comparisons,
        method="wilcox.test",
        size=2,
        method.args=list(alternative="greater"),
    ) +
    geom_text_repel(
        data = . %>% 
            filter(Gene=="XIST" | Gene == "FIRRE"| Gene == "ICCE"),
        aes(
            label=paste(Gene, round(100*diff,2)),
        ),
        min.segment.length = 0,
        size=2,
        nudge_x=.75,
        nudge_y=0.25,
    ) + 
    geom_text(
        data = summary_diff,
        aes(
            x=location,
            y=-0.8,
            label=paste0(
                " n = ", comma(n), "\n ",
                round(per_diff,2), "%"
            )
        ),
        vjust=1,
        hjust=0,
        size=1.75
    ) +
    facet_col(~sample)+
    scale_y_continuous("Percent difference between pat and mat transcripts", labels=percent) +
    scale_fill_manual(
        values=c(
            `other`=NA,
            `chrX`=NA,
            #`left of chrX BP`=NA,
            #`right of chrX BP`=NA,
            `chr8`=NA,
            `left of chr13 BP`="darkblue",
            `right of chr13 BP`="darkred"
        )
    )+
    my_grid() +
    theme(legend.position="none")

#ggadjust_pvalue(p,label = "{p.adj.format}{p.adj.signif}")
my_ggsave("Figures/transcript_violin_hap1_vs_hap2.pdf", height=5, width=5)

```

```{r}

summary_diff = chr13.df %>%
    group_by(bin) %>%
    summarise(
        per_diff=100*median(diff),
        n=n(),
    )

bins = unique(chr13.df$bin); bins

my_comparisons= list(
    c("other", "bin 1"),
    c("other", "bin 2"),
    c("other", "bin 3"),
    c("other", "bin 4"),
    c("left of chr13 BP", "bin 1"),
    c("left of chr13 BP", "bin 2"),
    c("left of chr13 BP", "bin 3"),
    c("left of chr13 BP", "bin 4")
)

chr13.df %>%
    ggviolin(y = "diff", x="bin",
        draw_quantiles = 0.5,
        rug = FALSE,
        fill="bin",
        alpha=0.5,
    ) +
    stat_compare_means(
        #label="{p.format}{p.signif}",
        #label.y = c(0.9, 0.9, 1, 1.1),
        comparisons=my_comparisons,
        method="wilcox.test",
        size=2,
        method.args=list(alternative="greater"),
    ) + my_grid() +
     geom_text(
        data = summary_diff,
        aes(
            x=bin,
            y=-0.8,
            label=paste0(
                " n = ", comma(n), "\n ",
                round(per_diff,3), "%"
            )
        ),
        vjust=1,
        hjust=0,
        size=1.75
    ) +
    scale_y_continuous("Percent difference between pat and mat transcripts", labels=percent) +
    my_grid() +
    theme(legend.position="none")
my_ggsave("Figures/transcripts_all_violin_hap1_vs_hap2.pdf")
```


```{r}
transcripts %>%
    filter(!grepl("_", chrom)) %>%
    group_by(chrom) %>%
    summarise(
        total_reads=n(),
        phased_reads=sum(!is.na(HP)),
        h1_reads=sum(HP=="1", na.rm=T),
        h2_reads=sum(HP=="2", na.rm=T),
        phase_diff = 100*(h1_reads/phased_reads - h2_reads/phased_reads),
    ) %>%
    print(.,n=30)
```