---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
system("mkdir -p Figures")
system("mkdir -p Tables")
source('Rscripts/utils.R')
```
# IGNORE
```{r}
df=fread("Tables/raw-hap1-vs-hap2-accessability.tsv")
# fix the mat pat flipped haps
tdf = copy(df)
cond = df$sample !="UDN318336"
h1=grep("hap1", colnames(df))
h2=grep("hap2", colnames(df))
for(i in seq(length(h1))){
    c1 = h1[i]
    c2 = h2[i]
    df[cond][[c1]] = tdf[cond][[c2]]
    df[cond][[c2]] = tdf[cond][[c1]]
}
# continue 
df$hap1_cov = df$hap1_acc + df$hap1_link + df$hap1_nuc
df$hap2_cov = df$hap2_acc + df$hap2_link + df$hap2_nuc
df$hap1_frac_acc = df$hap1_acc/df$hap1_cov
df$hap2_frac_acc = df$hap2_acc/df$hap2_cov
df$autosome = "Autosome"
df[ct == "chrY"]$autosome = "chrY"
df[ct == "chrX"]$autosome = "chrX"
df
sum(df$imprinted)
sd = 3
pdf = df %>%
    mutate(
        id = seq(n()),
        min_cov = pmax(cov/2 - sd * sqrt(cov/2), 10),
        max_cov = cov/2 + sd * sqrt(cov/2),
    ) %>%
    filter(autosome != "chrY" ) %>%
    filter(hap1_cov > min_cov & hap2_cov > min_cov) %>%
    filter(hap1_cov < max_cov & hap2_cov < max_cov) %>%
    mutate(
        hap1_nacc = hap1_cov - hap1_acc,
        hap2_nacc = hap2_cov - hap2_acc,
    ) %>%
    rowwise() %>%
    mutate(
        p_value=fisher.test(matrix(c(hap1_acc, hap1_nacc, hap2_acc, hap2_nacc),nrow=2))$p.value
    ) %>%
    group_by(sample)%>%
    mutate(
        #p_cor = p_value * n(),
        p_adjust = p.adjust(p_value, method="BH"),
    ) %>%
    select(!starts_with("V")) %>%
    mutate(
        diff = hap1_frac_acc - hap2_frac_acc,
    ) %>%
    data.table()
```


```{r}
library(valr)
f="results/GM12878_130X/hap1-vs-hap2/FIRE.hap.differences.bed"
a=my_read_bed(f)
f="results/UDN318336/hap1-vs-hap2/FIRE.hap.differences.bed"
b=my_read_bed(f)
f="results/GM12878_pacbiome/hap1-vs-hap2/FIRE.hap.differences.bed"
c=my_read_bed(f)
f="results/HG002_pacbiome/hap1-vs-hap2/FIRE.hap.differences.bed"
d=my_read_bed(f)
imprinted=my_read_bed("data/lcl_dmr_coordinates_Akbari.bed")
pdf=bind_rows(
    list(a,b,c,d)
    ) %>%
    bed_map(imprinted, imprinted=(length(V4) > 0)) %>%
    replace_na(list(imprinted=FALSE)) %>%
    group_by(sample)%>%
    mutate(
        #p_cor = p_value * n(),
        p_adjust = p.adjust(p_value, method="BH"),
    ) %>%
    data.table()

tdf = copy(pdf)
cond = pdf$sample !="UDN318336"
h1=grep("hap1", colnames(pdf))
h2=grep("hap2", colnames(pdf))
for(i in seq(length(h1))){
    c1 = h1[i]
    c2 = h2[i]
    pdf[cond][[c1]] = tdf[cond][[c2]]
    pdf[cond][[c2]] = tdf[cond][[c1]]
}

pdf
```

```{r}
make_hap_plots = function(SM, show_imprinted=FALSE, p_threshold = 0.05){
    tdf = pdf %>%
        filter(sample==SM) 
    tdf %>%
        ggplot(aes(x=hap1_frac_acc, y=hap2_frac_acc)) +
        stat_cor(size=2) +
        geom_hex(bins=75) +
        geom_abline(aes(intercept=0, slope=1), linetype="dashed")+
        scale_fill_distiller("", palette = "Spectral", trans="log10") +
        scale_x_continuous("Paternal accessibility", labels=percent) +
        scale_y_continuous("Maternal accessibility", labels=percent) +
        #annotation_logticks(sides="lb") +
        facet_wrap(~autosome, ncol=2)+
        my_grid()
    my_ggsave("Figures/{SM}_hap1_vs_hap2.pdf", height=3, width=6)
    
    cor_p_threshold = max(tdf[p_adjust <= p_threshold]$p_value)
    y_lim = ceil( max(-log10(tdf$p_value)))
    y_by = 1 
    if(y_lim > 10){
        y_by = 2
    }
    # add p-value col, volcano plot
    n=comma(nrow(tdf))
    p = tdf %>%
        ggplot(aes(x=diff, y=p_value)) +
        geom_hex(bins=100) + scale_fill_distiller("", palette = "Spectral", trans="log10") +
        geom_hline(aes(yintercept=(p_threshold)), linetype="dashed", color="darkblue")+
        geom_hline(aes(yintercept=(cor_p_threshold)), linetype="dashed", color="darkred")+
        facet_wrap(~autosome, ncol=2)+
        scale_x_continuous("Difference between paternal and maternal accessibility", labels=percent) +
        scale_y_continuous(
            glue("p-value   (n = {n})"), 
            #labels=comma,
            breaks=10**(-seq(0, y_lim, y_by)),
            minor_breaks=10**(-seq(0, y_lim, 0.1)),
            trans=reverselog_trans(10),
            labels=scientific_10,
        ) + 
        my_grid()
    if(show_imprinted){
        p + geom_point(
            data=tdf%>% 
                filter(imprinted>0, p_value <= 0.05),
            aes(x=diff, y=p_value),
            shape="+",
            #alpha=0.75,
            color="darkred",
        )
    }
    my_ggsave("Figures/{SM}_volcano_hap1_vs_hap2.pdf", height=3, width=5)
}
SM="GM12878_pacbiome"
make_hap_plots(SM, show_imprinted=TRUE)
SM="HG002_pacbiome"
make_hap_plots(SM, show_imprinted=TRUE)
SM="GM12878_130X"
make_hap_plots(SM, show_imprinted=TRUE)
SM="UDN318336"
make_hap_plots(SM, show_imprinted=TRUE)
```

```{r}
pdf %>% 
    group_by(sample) %>%
    arrange(p_adjust) %>% 
    fwrite(glue("Tables/hap1-vs-hap2-accessability.tsv.gz"), sep="\t")
```

