---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
# get a fire peak data table called `df`
source("Rscripts/Fire-peak-df.R")
```

```{r}
percent_encode = fire_df %>% 
    group_by(group) %>%
    summarise(
        `% in\nENCODE` = 100*mean(encode_count>0),
        `% in\nSDs`=100*mean(sd_count>0),
        `% in\nTSS`=100*mean(TSS>0),
        #`% of genome\n(c)`=100*sum(end-start)/3.1e9,
        `% of\ngenome\n(cumulative)`=100*max(Mbp*1e6)/3.1e9,
        `# of\npeaks`=n(),
        acc_percent=unique(group)+0.025,
        Mbp = sum(end-start)/1e6,
    ) %>%
    filter(`# of\npeaks` > 2)

cur_colors = c(
            `% in\nENCODE`="darkgreen",
            `% in\nTSS`="darkblue",
            `% in\nSDs`="darkred",
            `% of\ngenome\n(cumulative)`="darkgray",
            `# of\npeaks`="darkcyan"
            )
cur_colors
percent_encode_long = percent_encode %>%
    pivot_longer(
        cols=names(cur_colors)
        )

percent_encode_long

percent_plots = percent_encode_long %>%
    mutate(
        name=factor(name, levels=names(cur_colors))
    ) %>%
    ggplot(aes(x=acc_percent, y=value, group=name, fill=name)) +
    geom_bar(stat="identity", color="black")+
    geom_text(
        aes(
            x=acc_percent,
            label=sub("\\.0+$", "", comma(value, accuracy=0.01)),
        ),
        #min.segment.length=1,
        #direction="y",
        #alpha=0.5,
        vjust=-0.3,
        #color="white",
        #nudge_y=0.01,
        size=1
    ) +
    scale_y_continuous("", label=comma) +
    scale_x_continuous(
        "",
        breaks=seq(5,100,5)/100,
        label=rep("",20),
    )+
    scale_fill_manual(values=cur_colors) + 
    facet_col(~name, scales="free_y", strip.position = "left") + 
    my_grid() +
    coord_cartesian(xlim=c(0,1), clip=FALSE)+
    theme_no_x() +
    theme(legend.position="None")

my_ggsave("Figures/peaks-vs-percent.pdf", height=3, width=5)
```

```{r}
x = fire_df %>% 
    separate_rows(encode_anno, sep=";") %>%
    group_by(group, encode_anno) %>%
    summarise(
        count=n()   
    ) %>%
    group_by(
        group
    ) %>%
    filter(sum(count)>20) %>%
    mutate(
        percent=100*count/sum(count)
    )

encode %>%
    group_by(component) %>%
    summarise(count=n(),percent = sum(end-start)/1e6) %>%
    mutate(
        #group="control",
        encode_anno=component,
        percent = percent/sum(percent)*100
    ) %>%
    arrange(percent) %>%
    merge(x, by="encode_anno") %>%
    filter(count.y>300) %>%
    data.table() %>%
    mutate(
        lfc = log2(percent.y) - log2(percent.x)
    ) %>%
    arrange(-lfc)


plot_encode_anno=x %>% 
    filter(!is.na(encode_anno)) %>%
    ggplot(
        aes(
            x=group+0.025,
            weight=count,
            fill=encode_anno,
        )
    ) +
    geom_bar(
        position="fill",
        width=0.0495,
    ) +
    scale_x_continuous(
        "",
        breaks=seq(5,100,5)/100,
        label=rep("",20),
    )+
    scale_y_continuous("")+
    scale_fill_manual(
        "", 
        values=as.vector(glasbey(length(unique(encode$component)))),
        guide=guide_legend(nrow=2)
    )+
    coord_cartesian(xlim=c(0,1))+
    my_grid()+
    theme(
        legend.text=element_text(size=3),
        legend.key.size=unit(1, "mm"),
        legend.position="top",
        plot.margin = unit(c(0, 0, 0, 0), "cm"),
    )
kk=plot_encode_anno+plot_spacer()+percent_plots+plot_layout(heights = c(1,-0.3, 3))
my_ggsave("Figures/peaks-vs-encode-annotations.pdf", height=4, width=6, plot=kk)
```


```{r}
by_5_per = fire_df %>%
    group_by(group) %>%
    slice_max(order_by = n, n = 1)

lookup=fire_df$Mbp
names(lookup)=fire_df$n
#lookup
my_scale_function=function(x){
    lookup[x]
}

pecdf=fire_df %>%
    arrange(-acc_percent, -n) %>%
    #filter((n+1)%%100==0) %>%
    ggplot(aes(x=acc_percent, y=n)) +
    geom_line()+
    geom_text_repel(
        data = fire_df %>% filter(n==max(n)),
        aes(
            x=min_percent_acc,
            label=paste(
                "Limit of detection", percent(min_percent_acc, accuracy=0.01),
                "\n# peaks", comma(n)
            ),
        ),
        min.segment.length=0,
        segment.size=0.2,
        direction="y",
        size=1.5,
        nudge_y=-1.0,
        #nudge_x=0.1,
    ) +
    geom_text_repel(
        data=by_5_per,
        aes(
            x=acc_percent,
            label=paste(
                comma(n)
            ),
        ),
        min.segment.length=0,
        direction="x",
        nudge_x=0.1,
        segment.size=0.1,
        size=1
    ) +
    scale_y_continuous(
        "# of regulatory elements\nin the genome",
        trans="log10",
        label=comma,
         # Add a second axis and specify its features
       #sec.axis = sec_axis(
       #     ~my_scale_function(.),
       #     name="Mbp",
       #     label=comma,
        #)
    ) + 
    annotation_logticks(side="l")+
    scale_x_continuous(
        "Minimum % of fibers that are accessible",
        breaks=seq(5,100,5)/100,
        label=percent,
        #guide = guide_axis(n.dodge = 2),
    ) +
    my_grid() +
    coord_cartesian(xlim=c(0,1), ylim=c(100,NA)) 



p=plot_encode_anno+plot_spacer()+percent_plots+pecdf+plot_layout(heights = c(1,-0.5, 3, 2))
my_ggsave("Figures/peaks-vs-percent.pdf", height=4, width=5)
```

# ATAC
```{r}
fire_df %>%
    filter(atac_max > 0) %>%
    ggplot(aes(x=atac_max, y=acc_percent)) +
    geom_hex(bins=30) +
    scale_fill_distiller("", palette = "Spectral", trans="log10") +
    stat_cor()+
    #geom_smooth(method="lm", se=F) +
    #facet_wrap(~autosome, ncol=2)+
    #facet_wrap(~group)+
    scale_x_continuous(
        "FIRE peak score",
        #labels=comma,
        trans="log10",
    ) +
    scale_y_continuous(
        "ATAC signal",
        labels=percent,
        #trans="log10",
    ) + 
    my_grid()
my_ggsave("Figures/ATAC-vs-FIRE.pdf", height=3, width=4)
```



# dnase
```{r}
fire_df %>%
    filter(dnase_max > 0) %>%
    ggplot(aes(x=score, y=dnase_max+1)) +
    geom_hex(bins=30) +
    scale_fill_distiller("", palette = "Spectral", trans="log10") +
    stat_cor()+
    geom_smooth(method="lm", se=F) +
    #facet_wrap(~autosome, ncol=2)+
    #facet_wrap(~group)+
    scale_x_continuous(
        "FIRE peak score",
        labels=comma,
        #trans="log10",
    ) +
    scale_y_continuous(
        "DNase signal",
        labels=comma,
        trans="log10",
    ) + 
    my_grid()
my_ggsave("Figures/DNase-vs-FIRE.pdf", height=3, width=4)
```

# dnase by peak size
```{r}
fire_df %>% mutate(
        psize=end-start,
        size_group = cut(psize, breaks=c(0,200,250,300,Inf)),
        size_group2=size_group,
    ) %>%
    filter(chrom != "chrX", chrom != "chrY", is_dnase_peak) %>%
    filter(dnase_max > 0) %>%
    pivot_longer(starts_with("dnase_max")) %>%
    #filter(dnase_max>0.3) %>%
    group_split(name,size_group) %>% 
    map(
        ~ggplot(., aes(x=value, y=acc_percent)) +
            geom_hex(bins=50) + 
            #geom_smooth(se=F, method="lm", linetype="dashed", size=1)+
            scale_fill_distiller("", 
                palette = "Spectral",
                #trans="log10"
            ) +
            stat_cor(size=2.5)+
            scale_x_continuous(
                "DNase peak signal", 
                trans="log10"
            ) + 
            scale_y_continuous("% actuation in Fiber-seq data", label=percent) + 
            annotation_logticks(side="b") + 
            my_grid() +
            ggtitle(paste(unique(.$size_group2), "   n=",comma(nrow(.)),sep=""))+
            theme(
                legend.position="left",
                plot.title = element_text(size=5, face="bold"),
                aspect.ratio=1,
            )
    ) %>% 
    plot_grid(plotlist = ., align = 'hv', ncol = 4)
        
my_ggsave("Figures/FIRE-peaks-percent-fire-vs-DNase.pdf", height=3, width=7)
```

# ATAC by peak size
```{r}
fire_df %>% mutate(
        psize=end-start,
        size_group = cut(psize, breaks=c(0,200,250,300,Inf)),
        size_group2=size_group,
    ) %>%
    filter(chrom != "chrX", chrom != "chrY") %>%
    filter(atac_max > 100) %>%
    pivot_longer(starts_with("atac_max")) %>%
    #filter(dnase_max>0.3) %>%
    group_split(name,size_group) %>% 
    map(
        ~ggplot(., aes(x=value, y=acc_percent)) +
            geom_hex(bins=50) + 
            #geom_smooth(se=F, method="lm", linetype="dashed", size=1)+
            scale_fill_distiller("", 
                palette = "Spectral",
                #trans="log10"
            ) +
            stat_cor(size=2.5)+
            scale_x_continuous(
                "ATAC peak signal", 
                trans="log10"
            ) + 
            scale_y_continuous("% actuation in Fiber-seq data", label=percent) + 
            annotation_logticks(side="b") + 
            my_grid() +
            ggtitle(paste(unique(.$size_group2), "   n=",comma(nrow(.)),sep=""))+
            theme(
                legend.position="left",
                plot.title = element_text(size=5, face="bold"),
                aspect.ratio=1,
            )
    ) %>% 
    plot_grid(plotlist = ., align = 'hv', ncol = 4)
        
my_ggsave("Figures/FIRE-peaks-percent-fire-vs-ATAC.pdf", height=3, width=7)
```



# dnase with gc in extreams
```{r}

dnase_peaks_with_gc = fire_df %>%
    filter(T) %>% filter(end-start > 300, acc_percent > 0.85) 

z=dnase_peaks_with_gc %>% 
    ggplot(., aes(x=GC_frac, y=dnase_max)) +
        geom_hex(bins=50) + 
        geom_smooth(se=F)+
        scale_fill_distiller("", 
            palette = "Spectral",
            trans="log10"
        ) +
        stat_cor(size=2.5)+
        scale_y_continuous(
            "DNase signal in large (> 300bp)\n highly accessible (> 85%) FIRE peaks", 
            trans="log10"
        ) + 
        scale_x_continuous("GC content", label=percent) + 
        annotation_logticks(side="l") + 
        my_grid() 
my_ggsave("Figures/DNase-vs-GC-extreme.pdf", height=2, width=2.75)
```



# number of regulatory elements per cell
```{r}
comma(sum(fire_df$acc_percent)*2)
```



# 10bp df that andrew doesnt like
```{r}
bp = fread("data/bedgraph_annotations/bo.10bp.bed.gz", nThread=8)

bp[, c("chrom", "start", "end") := tstrsplit(key, "_", fixed=TRUE, type.convert=TRUE)]
bp$mid = floor((bp$start + bp$end)/2)
bp$position = bp$st - bp$mid
dim(bp)/1e6
bp

df_bp = merge(bp, df[, c("chrom", "start", "end", "group")], by=c("chrom", "start", "end")) %>%
    replace_na(list(ENCFF658WKQ_DNase = 0)) %>%
    pivot_longer(
        cols = starts_with("EN", ignore.case = FALSE),
        names_to= "exp",
        values_to="coverage",
    ) %>%
    filter(!is.na(coverage)) %>%
    data.table
df_bp
```
```{r}
width=500
width=1000
smooth=10
#df_bp %>% group_by(group) %>% summarise(length(unique((key))))
p.df = df_bp %>% 
    filter(chrom != "chrY", chrom != "chrX") %>%
    filter(position > -width & position < width) %>%
    filter(exp=="ENCFF658WKQ_DNase") %>%
    mutate(
        position = smooth * floor(position/smooth),
    ) %>%
    group_by(position, exp, group) %>%
    summarise(
        n_sites = length(unique(key)),
        value = sum(coverage),
    ) %>%
    group_by(group, exp) %>%
    mutate(
        n_sites=mean(n_sites),
        value2 = value/mean(n_sites),
    ) %>%
    filter(n_sites>100) %>%
    arrange(exp, group, position) 

mmin=min(p.df$group)
mmax=max(p.df$group)
labels = seq(mmin,mmax,0.05)
labels
z = p.df %>% 
    ggplot(
        aes(
            x=position, 
            y=value2,
            #weight=coverage,
            #color=factor(`group`),
            color=`group`-0.5,
            fill=NULL, 
            group=group
        )
    ) +
    geom_line(linewidth=0.2)+
    #geom_density(alpha=0.8, linewidth=.3) +
    #facet_wrap(~exp, scales="free")+
    scale_x_continuous("Relative position") +
    scale_y_continuous("DNase read count", trans="log10") + annotation_logticks(side="l")+
    scale_colour_steps2("", breaks=labels-0.5,  labels=labels) +
    my_grid() +
    theme(
        #legend.position="top",
        legend.key.size=unit(0.2, "inch")
    )
my_ggsave("Figures/DNase-over-FIRE-peaks.pdf", height=2, width=3)
```

```{r}
smooth = 10
z=df_bp %>%
    filter(group == 0.20) %>%
    #head(1e6) %>%
    #filter(group > 0.50) %>%
    filter(!is.na(coverage)) %>%
    filter(position > -width & position < width) %>%
    #group_by(group, position, exp) %>%
    #summarise(
    #    n_sites = length(unique(key)),
    #    coverage = sum(coverage),
    #) %>%
    ggplot(
        aes(
            x=position, 
            y=coverage,
            #weight=coverage,
            #color=factor(`group`),
            #color=`group`-0.5,
        )
    ) +
    #geom_line(alpha=0.1)+
    geom_hex(bins=300) + scale_fill_distiller("", palette = "Spectral", trans="log10")+
    #geom_density(alpha=0.8, linewidth=.3) +
    facet_wrap(~exp, scales="free")+
    scale_x_continuous("Relative position") +
    #scale_y_continuous("Relative position", trans="log10") +
    scale_y_continuous("Relative position", limits=c(0,50)) +
    #scale_colour_steps2(n.breaks=20, nice.breaks=TRUE) +
    my_grid() 
my_ggsave("Figures/Other-DNase-over-FIRE-peaks.pdf", height=3, width=5)
```

```{r}
p.df[p.df$position==-width& p.df$exp=="ENCFF658WKQ_DNase",]
p.df[p.df$position==width-smooth& p.df$exp=="ENCFF658WKQ_DNase",]

df_bp %>%
    filter(group == 0.05) 
```



# make the dreaded heatmap
```{r}
f="Tables/per_site_windows_dnase_and_percent_fire.tbl.gz"
windows_near_fire_peaks = fread(f)
colnames(windows_near_fire_peaks) = c("window_chrom", "window_start", "window_end", "ID", "data Fiber-seq % accessible", "data DNase signal")
windows_near_fire_peaks 
```
```{r}
tFDR=0.01
peaks_to_sample = fire_df %>% filter(FDR < tFDR) %>% group_by(group) %>% sample_n(100) %>% select(group,ID) %>% data.table
sampled_windows_near_fire_peaks = merge(windows_near_fire_peaks, peaks_to_sample, by="ID") %>%
    pivot_longer(
        starts_with("data")
    ) %>%
    group_by(name) %>%
    mutate(
        value = percent_rank(value),
        name = str_remove(name, "data "),
    ) %>%
    dplyr::group_by(name, group, ID) %>%
    mutate(sort_val=mean(value)) %>%
    dplyr::ungroup() %>%
    dplyr::group_by(group) %>%
    arrange(sort_val) %>%
    mutate(
        n_id=as.numeric(factor(ID, levels=unique(ID))),
    ) %>%
    separate(ID, sep="_", into=c("peak_chrom", "peak_start", "peak_end"),  convert = T) %>%
    ungroup() %>%
    mutate(
        offset = window_start-peak_start,
        group=factor(group, levels=rev(sort(unique(group)))),
    ) %>%
    data.table()
sampled_windows_near_fire_peaks
data.table(table(sampled_windows_near_fire_peaks$n_id))
```

```{r}
xx=min(sampled_windows_near_fire_peaks$offset)
z = sampled_windows_near_fire_peaks %>%
    mutate(
        name = factor(name, levels=rev(unique(name)))
    ) %>%
    ggplot(aes(x=offset, y=n_id, fill=100*value)) +
    geom_raster(interpolate=TRUE)+
    facet_grid(vars(group),vars(name))+
    scale_fill_distiller(
        direction=1,
        #scale_fill_steps(
        "Percentile rank of data", 
        breaks=seq(0,100,10),
        #palette = "Spectral",
        #trans="log10",
    ) + 
    coord_cartesian(xlim=c(xx,-xx))+
    scale_y_continuous(
        "",
        #breaks=c(max(sampled_windows_near_fire_peaks$n_id)),
        breaks=c()
    ) +
    scale_x_continuous(
        "Distance from FIRE peak start", 
        labels=comma
    )+
    my_vgrid() +
    theme(
        legend.position="top",
        #legend.key.size = unit(1, "line"),
        legend.key.width = unit(1, "line"),
        panel.spacing = unit(.01, "lines"),
        strip.text.y = element_text(size = 4),
        strip.text.x = element_text(size = 6),
    )
my_ggsave("Figures/per-site-observations-FDR-{tFDR}.pdf", height=4, width=4)
```


```{r}
z=sampled_windows_near_fire_peaks %>%
    mutate(
        name = factor(name, levels=rev(unique(name)))
    ) %>%
    filter(offset > xx, offset < -xx ) %>%
    filter(!is.na(value)) %>%
    ggplot(aes(x=offset, weight=100*value, color=name)) +
    #geom_histogram(bins=200, position="identity")+
    geom_density()+
    #facet_col(~name, scales="free_y")+
    scale_x_continuous(limits=c(xx,-xx))+
    scale_y_continuous(limits=c(0,NA))+
    my_grid() +
    theme(
        legend.position="top"
    )
my_ggsave("Figures/per-site-observations-FDR-{tFDR}-density.pdf", height=3, width=3)
```














