---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
system("mkdir -p Figures")
system("mkdir -p Tables")
source('Rscripts/utils.R')
library(ggbeeswarm)

```


```{r}
imprinted=fread("data/lcl_dmr_coordinates_Akbari.bed")
g="../../../assemblies/hg38.analysisSet.fa.fai"
diffs="results/PS00272/hap1-vs-hap2/FIRE.hap.differences.bed"
tss="data/gencode.v42.annotation_TSS.gff3"
df=fread(cmd=glue("bedtools slop -b 1 -i {tss} -g {g} > tmp.bed; bedtools intersect -header -u -a {diffs} -b tmp.bed")) %>% filter(`#ct` == "chr15")
df

df$Label = "other"
df[en > 88603388 & st < 88605131]$Label = "LINC01586"
df[st > 88620681 & en < 88621873]$Label = "AEN"
df[st > 88545225 & en < 88547556]$Label = "DET1"
df[st > 88635357 & en < 88640684]$Label = "ISG20"

```
```{r}
df %>%
    filter(en > 86569421 & st <90569452) %>%
    arrange(diff) %>%
    #filter(hap1_acc + hap2_acc > 10) %>%
    mutate(
        x=seq(n()),
        alpha=case_when(
            Label == "other" ~ 0.5,
            TRUE ~ 1,
        )
    ) %>%
    #filter(p_value < 0.2) %>%
    ggplot(
        aes(x=x, y=diff, color = Label, alpha=alpha)
    ) +
    geom_text_repel(
        data = . %>% filter(Label!="other"),
        aes(label=paste(Label, "\nchr15:", st, "-", en,sep="")),
        size=2,
        min.segment.length=0, 
        nudge_x=-10
    ) +
    geom_point()+
    scale_x_continuous("Rank", label = comma) +
    scale_y_continuous("Difference in % acc in hap1 vs hap2", limits = c(-0.5,0.5))+
    scale_alpha_continuous(range=c(0.55,1))+
    theme_minimal_grid()
my_ggsave("Figures/PS00272.pdf")
```

```{r}
df %>%
    filter(en > 86569421-3e6 & st <90569452+3e6) %>%
    arrange(diff) %>%
    #filter(hap1_acc + hap2_acc > 10) %>%
    mutate(
        x=seq(n()),
        alpha=case_when(
            #Label == "other" ~ 0.5,
            p_value > 0.05 ~ 0.5,
            TRUE ~ 1,
        )
    ) %>%
    #filter(p_value < 0.2) %>%
    ggplot(
        aes(x=st, y=diff, color = Label, alpha=alpha)
    ) +
    geom_text_repel(
        data = . %>% filter(Label!="other"),
        aes(label=paste(Label, "\nchr15:", st, "-", en,"\n",round(p_value,4), sep="")),
        size=2,
        min.segment.length=0, 
        #nudge_x=-10
    ) +
    geom_point()+
    scale_x_continuous("Genomic position", label = comma) +
    scale_y_continuous("Difference in % acc in hap1 vs hap2", limits = c(-0.5,0.5))+
    scale_alpha_continuous(range=c(0.55,1))+
    theme_minimal_grid()
my_ggsave("Figures/PS00272_pos.pdf", width=8)
```


```{r}
df %>%
    filter(en > 86569421 & st <90569452) %>%
    arrange(diff) %>%
    #filter(hap1_acc + hap2_acc > 10) %>%
    mutate(
        x=seq(n()),
        alpha=case_when(
            #Label == "other" ~ 0.5,
            p_value > 0.05 ~ 0.05,
            TRUE ~ 1,
        )
    ) %>%
    #filter(p_value < 0.2) %>%
    ggplot(
        aes(x="x", y=diff, color = Label, alpha=alpha, group="1", fill=NULL)
    ) +
    #geom_point()+
    geom_violin() + 
    #geom_quasirandom() +
    geom_beeswarm(corral.width = 0.9, cex=8, size=3)+
    #scale_x_continuous("Rank", label = comma) +
    scale_y_continuous("Difference in % acc in hap1 vs hap2", limits = c(-0.5,0.5))+
    scale_alpha_continuous(range=c(0.35,1))+
    theme_minimal_grid()
my_ggsave("Figures/PS00272_swarm.pdf")
```



```{r}
df %>%
    #filter(en > 86569421 & st <90569452) %>%
    #filter(`#ct` == "chr16") %>%
    arrange(diff) %>%
    #filter(hap1_acc + hap2_acc > 10) %>%
    mutate(
        x=seq(n()),
        alpha=case_when(
            #Label == "other" ~ 0.5,
            p_value > 0.05 ~ 0.05,
            TRUE ~ 1,
        )
    ) %>%
    #filter(p_value < 0.2) %>%
    ggplot(
        aes(x="x", y=diff, color = Label, alpha=alpha, group="1", fill=NULL)
    ) +
    #geom_point()+
    geom_violin(width=1) + 
    #geom_quasirandom() +
    geom_beeswarm(corral.width = 0.8, cex=2, size=3)+
    #scale_x_continuous("Rank", label = comma) +
    scale_y_continuous("Difference in % acc in hap1 vs hap2")+
    scale_alpha_continuous(range=c(0.35,1))+
    theme_minimal_grid()
my_ggsave("Figures/PS00272_all_swarm.pdf")
```