name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # pixi test
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.37.0
          cache: true
      - run: pixi run test
